### ISSUE TITLE
404 error on API session route

### ISSUE THREAD

**Issue by SeraVault** [nuxt-modules/supabase#39] opened 2022-05-21 23:16 UTC
When trying to login to supabase using useSupabaseClient() using v0.1.14, I'm getting a 404 error:

POST http://localhost:3000/api/_supabase/session 404 (Page not found: /api/_supabase/session)

It works fine on v 1.1.10.  Is there any additional configuration necessary on v0.1.14?

Thanks

**Comment by larbish** [comment] 2022-05-23 08:22
Hi @SeraVault, nothing has changed on login between those two versions. Can you provide a reproduction ?

**Comment by Atinux** [comment] 2022-05-23 09:57
How do you deploy your project @SeraVault ?

**Comment by SeraVault** [comment] 2022-05-24 03:00
I'm just using a local dev server at the moment (node run dev).  I'll see if I can provide a reproduction.  Thanks.

**Comment by daanvangeloven** [comment] 2022-05-27 09:24
I am currently struggling with the same issue. Has a cause been for this issue been found?
When I try magic link login on my local dev server I get this line in console: 
[Vue Router warn]: No match found for location with path "/api/_supabase/session"

The url looks like this after the issue:
http://localhost:3000/login#error_code=404&error_description=User+not+found

I had not changed anything on the login side when it stopped working. I tried reverting the module to 1.1.10 as stated above but that also didn't fix my issue.

**Comment by princeV** [comment] 2022-06-03 16:43
@[SeraVault](https://github.com/SeraVault)
I had the same issue and it was just that i missed to update the supabase auth settings with the github infos:
github:
![image](https://user-images.githubusercontent.com/7444074/171908535-0a251e07-432f-4c79-b627-4bee5c9c985e.png)

then update supabase under github enabled:
![image](https://user-images.githubusercontent.com/7444074/171908210-350db5a7-c3f2-4de9-ade3-08b50218fc77.png)

this helped me to get rid of the 404...

**Comment by nberlette** [comment] 2022-06-03 17:14
I was going to open a new issue, but I believe I've encountered ***this*** issue on the auth flow of the demo site itself. Check out this 5 second recording I've made below:


https://user-images.githubusercontent.com/11234104/171913428-29c5cd79-109d-4610-86f6-07ad6f56f51f.mov

**Comment by larbish** [comment] 2022-06-03 19:06
@nberlette concerning the demo, I tried something in local and have updated the auth redirect URL of the supabase dashboard to `localhost:3000`. I simply forgot to set it back to the good URL afterward. Sorry for that, it should be fixed.

**Comment by nddr** [comment] 2022-06-29 16:26
I've been having this same issue using Discord and Google auth. It was perfectly for a while, and a month or so ago, it just stopped working and I receive these errors in the console.

`POST http://localhost:3000/api/_supabase/session 404 (Not Found)`

```
Uncaught (in promise) FetchError: 404 Not Found (/api/_supabase/session)
    at async Object.callback (supabase.client.mjs:22:7)
```

Last night I reset Discord creds to test, but still same issue :/

**Comment by offeronhomes** [comment] 2022-06-29 20:32
I was experiencing the same issue and when i went back to 0.1.10 is started working again. huh. Will provide my repo soon.

**Comment by nddr** [comment] 2022-07-04 04:15
Reverting `@nuxtjs/supabase` to `0.1.10` has worked for me

**Comment by larbish** [comment] 2022-10-22 10:04
Are you still facing this issue with `v0.2.0` ?

**Comment by nddr** [comment] 2022-10-22 12:32
@larbish I am not. It is working well.

**Closed** 2022-10-24 07:04 UTC
Labels: question

**Comment by peterkimzz** [comment] 2022-12-06 11:12
Hi, @larbish 

I got same issue in only production mode, not localhost.

```ts
const { data, error } = await supabase.auth.verifyOtp({
    type: "magiclink",
    email: form.email,
    token: form.token,
  });

console.log(data)
```

The `console.log` shows an user's data successfully, but failed to request `/api/_supabase/session` only in production. So `SupabaseUser()` has noting.

Here is my info,

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `tailwindcss`, `supabase`
- Runtime Modules:  `@nuxtjs/supabase@0.3.0`, `@nuxtjs/tailwindcss@6.1.3`
- Build Modules:    `-`
------------------------------

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/20244536/205895698-a7e3f6b4-7b4e-44c0-9f84-c53dc30b8384.png">

**Comment by Atinux** [comment] 2022-12-06 13:29
@peterkimzz what command do you use to deploy your Nuxt app?

**Comment by peterkimzz** [comment] 2022-12-07 02:27
@Atinux I didn't override any option of the Nuxt project configuration. Just create a projecy by Vercel guideline.

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev -p 3003",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "test": "nuxt typecheck"
  },
  "devDependencies": {
    "@nuxtjs/supabase": "0.3.0",
    "@nuxtjs/tailwindcss": "6.1.3",
    "@tailwindcss/forms": "0.5.3",
    "husky": "8.0.2",
    "nuxt": "3.0.0"
  },
  "dependencies": {
    "@heroicons/vue": "2.0.13",
    "@supabase/supabase-js": "2.1.1"
  }
}

```

<img width="931" alt="image" src="https://user-images.githubusercontent.com/20244536/206072617-5e8da246-968a-4dde-baac-16185e21b3ac.png">

**Comment by mmartinsolisdev** [comment] 2022-12-07 21:23
I have the same error when deploying to production on Netlify or Cloudflare Pages. Everything works fine locally.
I have tried `npm run build` and `npm run generate` commands and they both have the same result when my app is deployed and I try to logIn with Google.

Netlify error
`POST https://admirable-baklava-3c95f7.netlify.app/api/_supabase/session 404`

Cloudflare error
```
POST https://burpeefly.pages.dev/api/_supabase/session 405
Uncaught (in promise) FetchError: 405  (/api/_supabase/session)
    at async Object.callback (entry.af57154f.js:5:118018)
```
```

My package.json
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/supabase": "^0.3.0",
    "@vicons/ionicons5": "^0.12.0",
    "naive-ui": "^2.33.4",
    "nuxt": "^3.0.0"
  }
}
```

**Comment by marc-tech** [comment] 2023-02-05 01:16
same here can it be the SITE_URL / BASE_URL ?

**Comment by Atinux** [comment] 2023-02-07 12:37
We don't advice to use the Supabase module with `nuxt generate` since it's better to have an API endpoint running too for your app.

Leverage `nuxt build` for Netlify instead.

**Comment by marc-tech** [comment] 2023-03-27 00:35
it's a probleme with vercel, because of /api edge function proxy (i don't know yet how to resolve this issue)

**Comment by fdarkaou** [comment] 2023-07-14 11:29
I still have this issue, is there any fix for this?
